const ACTION_TYPES = {
  CREATE_TASK_ACTION: 'CREATETASK_TASK_ACTION',
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

  GET_TASKS_ACTION: 'GET_TASKS_ACTION',
  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',

  UPDATE_TASK_ACTION: 'UPDATE_TASK_ACTION',
  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',

  REMOVE_TASK: 'REMOVE_TASK',
};

export default ACTION_TYPES;
